name: sol-miner

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Jalan ulang setiap 6 jam

jobs:
  sshx1:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Start SSHX 1
        run: |
          for i in $(seq 1 10); do
            echo "Starting VPS $i..."
            curl -sSf https://sshx.io/get | sh -s run &
          done
          wait
  sshx2:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Start SSHX 1
        run: |
          for i in $(seq 1 10); do
            echo "Starting VPS $i..."
            curl -sSf https://sshx.io/get | sh -s run &
          done
          wait
  sshx3:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Start SSHX 1
        run: |
          for i in $(seq 1 10); do
            echo "Starting VPS $i..."
            curl -sSf https://sshx.io/get | sh -s run &
          done
          wait
  sshx4:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Start SSHX 1
        run: |
          for i in $(seq 1 10); do
            echo "Starting VPS $i..."
            curl -sSf https://sshx.io/get | sh -s run &
          done
          wait
  sshx5:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Start SSHX 1
        run: |
          for i in $(seq 1 10); do
            echo "Starting VPS $i..."
            curl -sSf https://sshx.io/get | sh -s run &
          done
          wait
